### PR TITLE
CRAFTERCMS-1899

### PR DESCRIPTION
**Pull request by dejan-brkic**
fixed issue

### CODE REVIEW

**Comment by russdanner** [comment]
Hi Dejan,

Before I merge this just wanted to get feedback on why the general lock service is better than conventional java locking?

/r

**Comment by russdanner** [comment]
BUMP, Dejan see question

**Comment by dejan-brkic** [comment]
General lock service is conventional java locking (using lock objects not synchronized calls) wrapped in our service class (not to repeat same code everywhere, instead we are just using one method call)

**Comment by dejan-brkic** [comment]
Fixed issue with securing urls for services

**Pull request merged**
