### PR TITLE
[studio] Add the new RTE to all bps #2631

### PR DESCRIPTION
**Pull request by jvega190**

### CODE REVIEW

**Review by alhambrav — CHANGES_REQUESTED** [review]
In the sample rte configs, we have
```
<templates>
            <template>
                <title>Test template 1</title>
                <content>Test 1</content>
            </template>
            <template>
                <title>Test template 2</title>
                <content>Test 2</content>
            </template>
        </templates>
```
but, the above is not found in the actual configs... Should this be removed from the samples?

**Comment by jvega190** [comment]
@alhambrav it is provided as an example of usage, but I don't think that is that common so I didn't add it to the configs. I kept it on the examples so it can be used if wanted. What do you think that is better?

**Comment by alhambrav** [comment]
@jvega190 ah.... I guess we could keep it as long as it works when used in the config?  I haven't used it before, unfortunately.

**Review by alhambrav — APPROVED** [review]

**Comment by sumerjabri** [comment]
We should consider:
- Video Center II <== should we do that one too
- Upgrade Manager <== this means it will add it to existing sites and BPs

**Pull request merged**
