### PR TITLE
[5099] [studio] Publisher stops if any single item in package does not exist in blob store

### PR DESCRIPTION
**Pull request by dejan-brkic**
Publishing from blob store does not block publishing anymore if content is not present

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/5099

### CODE REVIEW

**Comment by sumerjabri** [comment]
@jdrossl also, why doesn't this happen in v4?

**Review by jdrossl — APPROVED** [review]
I'm ok with the fix, but to me it looks like a symptom of a different issue. If you try to publish a .blob and the content doesn't exist in S3 it means something went wrong before the publish

**Comment by jdrossl** [comment]
@sumerjabri in v4 we did a refactor for the exception handling in blob store that could explain why it's different

**Comment by russdanner** [comment]
Confirmed

**Pull request merged**
