### PR TITLE
Improvement for upgrade process:

### PR DESCRIPTION
**Pull request by jdrossl**
- Move users from and unused group and then delete it

https://github.com/craftercms/craftercms/issues/2473

### CODE REVIEW

**Review by avasquez614 — APPROVED** [review]

**Review by sumerjabri — CHANGES_REQUESTED** [review]
Shouldn't this go into a new upgrade script 3.1.0.3 or at least into 3.1.0.2 after the `system_admin` group is officially created?
I know you're banking on the ID being 1, but isn't that also risky?
Why not do it after the group is created and using the group name to move users and delete the unused group. With name, we can't go wrong.

**Review by dejan-brkic — CHANGES_REQUESTED** [review]
1. Every time new change in the database is added must go with the new update script and increased patch version. Only if changes did not get to the public repository (`develop`) you can merge them to the latest update script.

2. Delete cannot go by id because the group was already removed from create DB script. Delete statement must go by group name. One delete statement on `group` table should be enough because of foreign key cascade constraint.

3. The update statement is incorrect for the same reason as point 2. It is possible that the system does not have the group.

**Comment by jdrossl** [comment]
@sumerjabri @dejan-brkic
1. does it make sense to add a new version just for content changes? we don't need to alter any table or column for this.

2 & 3. I'll change to avoid using ids, but we still need the update in case any user is still using that group.

**Comment by dejan-brkic** [comment]
Anyone who has passed to a newer version than the one where you want to apply change will not pick up update.
The update is incorrect because it is blindly assigning all users from a group id=2 to group id=1 which is system admin group (full access)

**Comment by sumerjabri** [comment]
@jdrossl I agree with Dejan. Please create a new SQL for this. Please use group names.

**Review by sumerjabri — APPROVED** [review]

**Comment by sumerjabri** [comment]
@dejan-brkic final review please

**Review by dejan-brkic — APPROVED** [review]
Looks ok

**Pull request merged**
